USE [master]
GO

/****** Object:  Database [Gestion_Etudiant]    Script Date: 24/02/2021 13:44:27 ******/
CREATE DATABASE [Gestion_Etudiant]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Gestion_Etudiant', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Gestion_Etudiant.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Gestion_Etudiant_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Gestion_Etudiant_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Gestion_Etudiant].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Gestion_Etudiant] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET ARITHABORT OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Gestion_Etudiant] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Gestion_Etudiant] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Gestion_Etudiant] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Gestion_Etudiant] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Gestion_Etudiant] SET  MULTI_USER 
GO

ALTER DATABASE [Gestion_Etudiant] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Gestion_Etudiant] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Gestion_Etudiant] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Gestion_Etudiant] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Gestion_Etudiant] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Gestion_Etudiant] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Gestion_Etudiant] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Gestion_Etudiant] SET  READ_WRITE 
GO

